---

name: Easy Button

on:
  push:
    branches: [ dls*, main, release-* ]

jobs:
  easy:
    runs-on: ubuntu-latest
    name: easy
    permissions:
      id-token: write
      contents: read

    steps:
      # Establish snapshot datestamp
      - name: Create snapshot datestamp and output parameters
        run: |
          echo "Branch: ${{ github.ref_name }}"
          # default: './tools/config/buildref-AAP_2.3.json'
          if [[ ${{ github.ref_name }} == release-* ]] ; 
          then 
            echo "This is a release branch"
            VERSION=`echo ${{ github.ref_name }} | awk -F"-" '{print $2}'`
            echo "Version is:" $VERSION
            BUILDREF='./tools/config/buildref-AAP_'$VERSION'.json'
          else
            echo "This is a main branch"
            BUILDREF='./tools/config/buildref-AAP_2.3.json'
          fi
          echo 'Build reference file is:' $BUILDREF
