---

name: Easy Button

on:
  push:
    branches: [ dls*, main, release-* ]

jobs:
  easy:
    runs-on: ubuntu-latest
    name: easy
    permissions:
      id-token: write
      contents: read

    steps:
      # Establish snapshot datestamp
      - name: Create snapshot datestamp and output parameters
        run: |
          echo "Branch: ${{ github.ref_name }}"
          # default: './tools/config/buildref-AAP_2.3.json'
          if [[ ${{ github.ref_name }} == release-* ]] ; 
          then 
            echo "This is a release branch"
          else
            echo "This is a main branch"
          fi
