---

name: Build

env:
  GCP_IMAGE_FAMILY: redhat-aoc-gcp
  BUILDREF: './tools/config/buildref-AAP_2.3.json'
  MANIFEST_FILE: './manifests/2.3.20230221'
  GCP_BUCKET: 'positronic-asimov'
  GCP_BUCKET_MARKETPLACE: 'asimov-marketplace'

on:
  push:
    branches: [ main, release-* ]

jobs:
  tester:
    runs-on: ubuntu-latest
    name: tester
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Run a test
        run: |
          echo ${{ github.ref_name }}
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo main!
          else
            echo not main!
          fi
